---
- name: install mysql
  apt: name={{ item }} state=present update_cache=yes
  with_items: packages

- name: start mysql
  service: name=mysql state=started enabled=true

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: create databases
  mysql_db:
    name: "{{ item }}"
    state: present
    encoding: utf8
    collation: utf8_general_ci
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: databases
